### sample
GET http://localhost:8080/api/v1/identities/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJzdWIiOiJiNGNmZGVkOC01Yjk2LTRlZjYtYjY3Mi1jYmIyOTQ2MzE4YWEiLCJpc3MiOiJhY2NvdW50cy5ob21lcGFydHkuY29tIiwiaWF0IjoxNjc1MTAyOTk4LCJleHAiOjE2NzUxODkzOTh9.zdVRTLu6c4QxPFxbw075z_dHvlhYl8_sNjfdrke6tYc
Content-Type: application/json
