spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

homeparty:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver33
      jdbc-url: jdbc:mysql://127.0.0.1:3306/homeparty_main
      username: root
      password: asdfasdfasdf
      maximum-pool-size: 3$


