spring:
  jpa:
    show-sql: true
    open-in-view: false
  cloud:
    aws:
#      아래 키 삭제한 것
#      credentials:
#        access-key: Axxx
#        secret-key: u7xxxxxxxxxxxxxxxx
#        profile-name: stratospheric
      region:
        static: ap-northeast-2
#      cloudwatch:
#        log-group: sample-spring

homeparty:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:38291/homeparty_main
      username: root
      password: mysql
      maximum-pool-size: 3


