spring:
  jpa:
    open-in-view: false

homeparty:
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DATASOURCE_MAIN_JDBC_URL}
      username: ${DATASOURCE_MAIN_USERNAME}
      password: ${DATASOURCE_MAIN_PASSWORD}
      maximum-pool-size: ${DATASOURCE_MAIN_MAXIMUM_POOL_SIZE}
  aws:
    s3:
      default-bucket: ${DEFAULT_BUCKET}

slack:
  error-webhook-uri: ${SLACK_ERROR_WEBHOOK_URI}
  user-webhook-uri: ${SLACK_USER_WEBHOOK_URI}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}
  cloudwatch:
    log-group: ${AWS_CLOUDWATCH_LOG_GROUP}
