spring:
  jpa:
    show-sql: true

homeparty:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver33
      jdbc-url: jdbc:mysql://127.0.0.1:38291/homeparty_main
      username: root
      password: mysql
      maximum-pool-size: 3


